name: build

on:
  push:
    branches: ["main"]

  pull_request:
  workflow_call:
    outputs:
      linux:
        description: "Linux and MacOS binaries"
        value: ${{jobs.build.outputs.artifact}}
jobs:
  build:
    name: darwin and linux
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel build -c opt //:all_platforms
          mv bazel-out/darwin_arm64-opt/bin/glibc-stubs-generator glibc-stubs-generator_darwin_arm64
          mv bazel-out/darwin_amd64-opt/bin/glibc-stubs-generator glibc-stubs-generator_darwin_amd64
          mv bazel-out/linux_arm64_musl-opt/bin/glibc-stubs-generator glibc-stubs-generator_linux_arm64_musl
          mv bazel-out/linux_amd64_musl-opt/bin/glibc-stubs-generator glibc-stubs-generator_linux_amd64_musl
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: linux
          retention-days: 1
          path: |
            glibc-stubs-generator_darwin_arm64
            glibc-stubs-generator_darwin_amd64
            glibc-stubs-generator_linux_arm64_musl
            glibc-stubs-generator_linux_amd64_musl
